apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
  annotations: {}
  labels: {}
description: staging
gke:
  cluster: projects/vast-bounty-394808/locations/us-central1-a/clusters/helm-cd-testing-stg
